### PR TITLE
add SVG icons to reusable components

### PR DESCRIPTION
**Pull request by chazkiker2**
Add a layout to the landing page at the SearchClass component (this is a small PR... trying to make it easier on reviewers and git merge)

### CODE REVIEW

**Comment by chazkiker2** [comment]
Screen Shot 2020-10-19 at 7 12 21 PM

**Comment by chazkiker2** [comment]
this page is finished for the time being. Once we flesh-out the Redux & connection to back-end, I'll circle back to add search functionality and search results IF we have time. (That will be a big task that may require more than one dev.)

**Comment by chazkiker2** [comment]
just realized that I still need form validation for the search bar... I'll do that later as well. starting on new components.

**Review by AshWren — APPROVED** [review]
Looks good, pulled down and nothing breaks. :)

**Pull request merged**
