### PR TITLE
Feature/manage class

### PR DESCRIPTION
**Pull request by chazkiker2**
basic layout finished for ClassManage component (manage-classes page).

Not functional yet, just laid out. I will add the muscle to it tomorrow, probably calling it a night.

### CODE REVIEW

**Comment by chazkiker2** [comment]
Screen Shot 2020-10-19 at 10 53 07 PM

**Comment by chazkiker2** [comment]
Style tweaks still remain, and the page does not yet let users actually ~manage~ their classes, but it does let them look at "their" classes (which I assigned to them... so).

But worth merging since layout is (mostly) finished. I'll create a new branch for functionality and whatnot tomorrow.

**Comment by chazkiker2** [comment]
only need one reviewer, but figured I'd mark all of you as reviewers so anyone can do it whenever they have a second. No rush on this one, I'm probably calling it a night for today.

**Review by saharj — APPROVED** [review]
LGTM
Also good idea to put ClassSearchHead in a separate file

**Pull request merged**
